export const Language = {
  English: {
    windowtitle: "SARSHUBE | THE COVID19 TRACKER",
    ttctitle: "TOTAL CASES ALL AROUND THE WORLD",
    cards: {
      totalcases: "TOTAL CASES",
      totaldeathcases: "TOTAL DEATH CASES",
      totalrecoveredcases: "TOTAL RECOVERED ",
      todaycases: "TODAY CASES",
      todaydeaths: "TODAY DEATHS",
      todayrecovered: "TODAY RECOVERED",
      activecases: "ACTIVE CASES",
      critical: "CRITICAL",
      globecases: "GLOBAL COVID19 CASES",
      covidstatsinyoucountry: "COVID STATS IN YOUR COUNTRY",
    },
    cosearch: "COVID19 STATS BY SEARCH",
    worldlist: "World List",
    table: {
      lvl: "LVL",
      country: "Country",
      continent: "Continent",
      flag: "Flag",
      population: "Population",
      tcases: "Total Cases",
      trec: "Total Recovered",
      tdeaths: "Total Deaths",
      tdcases: "Today Cases",
      tdrec: "Today Recovered",
      tddeaths: "Today Deaths",
      active: "Active Cases",
      critical: "Serious Critical",
      cpom: "Cases Per 1Mil",
      dpom: "Deaths Per 1Mil",
      apom: "Active Per 1Mil",
      rpom: "Recovered Per 1Mil",
      crpom: "Critical Per 1Mil",
      tests: "Tests",
      tpom: "Tests Per 1Mil",
      ocpp: "One Case Per Ppl",
      odpp: "One Death Ppl",
    },
  },
  French: {
    windowtitle: "SARSHUBE | LE TRACEUR COVID19",
    ttctitle: "TOTAL DES CAS PARTOUT DANS LE MONDE",
    cards: {
      totalcases: "TOTAL DES CAS",
      totaldeathcases: "TOTAL DES CAS DE DÉCÈS",
      totalrecoveredcases: "TOTAL RÉCUPÉRÉ ",
      todaycases: "CAS AUJOURD'HUI",
      todaydeaths: "DÉCÈS AUJOURD'HUI",
      todayrecovered: "AUJOURD'HUI RÉCUPÉRÉ",
      activecases: "CAS ACTIFS",
      critical: "CRITIQUE",
      globecases: "GLOBAL COVID19 CASES",
      covidstatsinyoucountry: "COVID STATS IN YOUR COUNTRY",
    },
    cosearch: "COVID19 STATS BY SEARCH",
    worldlist: "World List",
    table: {
      lvl: "LVL",
      country: "Country",
      continent: "Continent",
      flag: "Flag",
      population: "Population",
      tcases: "Total Cases",
      trec: "Total Recovered",
      tdeaths: "Total Deaths",
      tdcases: "Today Cases",
      tdrec: "Today Recovered",
      tddeaths: "Today Deaths",
      active: "Active Cases",
      critical: "Serious Critical",
      cpom: "Cases Per 1Mil",
      dpom: "Deaths Per 1Mil",
      apom: "Active Per 1Mil",
      rpom: "Recovered Per 1Mil",
      crpom: "Critical Per 1Mil",
      tests: "Tests",
      tpom: "Tests Per 1Mil",
      ocpp: "One Case Per Ppl",
      odpp: "One Death Ppl",
    },
    Arabic: {},
    Deutch: {},
  },
}
